spring.application.name=cafe-pos
server.port=8085

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/cafe_pos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Database Initialization
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
# Avoid failing if table already exists or inserts conflict
spring.sql.init.continue-on-error=true
